server:
  port: 8090
  servlet:
    context-path: /BootCMS
spring:
  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/bootcms?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    username: kemao_2
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:swim/gdkm/mapper/*.xml